#
# Module manifest for module 'EstimatePS'
#
# Generated by: shoff
#
# Generated on: 12.08.2021
#

@{
ModuleVersion = '$$TAG$$'
GUID = 'e9292caa-02ef-42d1-90e2-dc28ad73ae26'
Author = 'Stefan Hoffmann'
CompanyName = ''
Copyright = '(c) Stefan Hoffmann. All rights reserved.'
Description = 'EstimatePS allows to estimate durations based on text, e.g. tasks'
ScriptsToProcess = @('EstimatePS.psm1')
RootModule = 'EstimatePS.psm1'
FunctionsToExport = '*'
CmdletsToExport = @()
VariablesToExport = @()
AliasesToExport = @()
PrivateData = @{

    PSData = @{
        Tags = @('estimate')
        LicenseUri = 'https://github.com/stho32/Automatically-Estimating-Task-Durations/blob/main/LICENSE'
        ProjectUri = 'https://github.com/stho32/Automatically-Estimating-Task-Durations'
        # ReleaseNotes = ''
        # Prerelease = ''
    } # End of PSData hashtable

} # End of PrivateData hashtable

}

